### ISSUE TITLE
"None" value seen in WFH approval message

### ISSUE THREAD

**Issue by adwaith-webtrigon** [webtrigon/WorkX-feedback#3]
The approval message seems to have a hiccup in the Python logic

Request ID: tswwnL9Hj9sSqemKbSQsyZHc

<img width="604" alt="image" src="https://github.com/webtrigon/WorkX-feedback/assets/25192916/3d967f2e-9349-4403-9236-4d5e949d9041">

**Comment by navaneeth-webtribe** [comment]
@adwaith-webtrigon : This has been fixed and deployed to production.

**Comment by webtrigon** [comment]
As @navaneeth-webtribe mentioned this has been moved to production. So, closing the issue. @adwaith-webtrigon
